name: 更新简法主页壁纸
on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch: 
  #watch:
    #typs: started
  #push:
    #branches: [ main ]
  schedule:
    #- cron: '0,30 * * * *' 
    - cron: '10,30 * * * *' 

env:
  TZ: Asia/Shanghai  # 设置时区为上海（东八区

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python
          pip install lxml requests

      - name: Run Python script
        run: python main.py
