name: Run Python Script
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */5 * * *'  # 每5小时执行一次

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml requests

      - name: Run Python script
        run: python main.py
    
