
name: 标记壁纸状态
on:
  repository_dispatch:
    types: [trigger-hate]
  workflow_dispatch:
  #watch:
    #typs: started
  #push:
    #branches: [ main ]
  # schedule:
  #   - cron: '0,30 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python
          pip install lxml requests

      - name: Run Python script
        run: python updateHade.py ${{ github.event.client_payload.src }}
